### ISSUE TITLE
Clicking on function in doc search doesn't always navigate to correct function

### ISSUE THREAD

**Issue by Ejhfast** [Ejhfast/iris-agent#3]
Implement a direct id lookup, should not be using logistic regression model to do that mapping

**Comment by binbineow** [comment]
？

**Comment by Ejhfast** [comment]
in sidebar, search for "minimum"

top result is "minimum of {array}"

you click on "minimum or {array}" and "mean of {array}" appears in
documentation pane

but why???

classifier is stupid, it will do the right thing given just "minimum" query
but given "minimum of {array}" will map to function for mean (which also
contains the word "array", which apparently is more strongly weighted)

**Comment by Ejhfast** [comment]
Fixed in https://github.com/Ejhfast/iris-agent/commit/9a5d7d31ace214e70e0ed455590d51031901d74b
